---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-java-ehr-patient-pomr
  name: csi-java-ehr-patient-pomr
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-opd-patient-pomr
  type: ClusterIP
