---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-empi-ui-service
  name: csi-empi-ui-service
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-empi-ui
  type: ClusterIP
