---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-java-ehr-ip
  name: csi-java-ehr-ip
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-ehr-ip
  type: ClusterIP
